Update license classifier. (#221)
The old one is no longer accepted.

It's been shortened: https://pypi.org/classifiers/

HTTPError: 400 Client Error: Invalid value for classifiers. Error: 'License :: OSI Approved :: MIT Software License' is not a valid choice for this field for url: https://upload.pypi.org/legacy/
Signed-off-by: Tully Foote <tfoote@osrfoundation.org>